# Generated by Django 2.2.4 on 2019-08-16 18:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190816_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='content',
            field=wagtail.core.fields.StreamField([('caro', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('author', wagtail.core.blocks.CharBlock())])), ('video', wagtail.embeds.blocks.EmbedBlock())], label='caro')), ('text', wagtail.core.blocks.TextBlock(label='text'))]),
        ),
    ]
