# Generated by Django 2.2.4 on 2019-08-16 19:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_auto_20190816_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='id',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='content',
            field=wagtail.core.fields.StreamField([('caro', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('author', wagtail.core.blocks.CharBlock())])), ('video', wagtail.embeds.blocks.EmbedBlock())], label='caro')), ('title', wagtail.core.blocks.TextBlock(label='title'))]),
        ),
    ]
